---
- name: AWS Instance Creation
  hosts: localhost
  gather_facts: true
  connection: local
  vars_files:
    - group_vars/dev/main.yml
  roles:
  - role: build_instances

- name: AWS Instance Update
  hosts: launched
  gather_facts: true
  roles:
  - role: update_instance
 
 
- name: AWS Cleanup
  hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
    - group_vars/dev/main.yml
  roles:
  - role: cleanup
